source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

def shared_pods
    use_frameworks!
    
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'MBProgressHUD'
    pod 'SwiftyBeaver'
    pod 'Disk'
    pod 'RealmSwift'
    pod 'SwiftMessages'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Google-Mobile-Ads-SDK'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Messaging'
end

target 'Application' do
  use_frameworks!
  shared_pods
end

target 'ApplicationTests' do
    shared_pods
end

target 'ApplicationUITests' do
    shared_pods
end
