source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

def shared_pods
    use_frameworks!
    
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'MBProgressHUD'
    pod 'SwiftyBeaver'
end

target 'Application' do
  use_frameworks!
  shared_pods
end

target 'ApplicationTests' do
    shared_pods
end

target 'ApplicationUITests' do
    shared_pods
end
